### ISSUE TITLE
SeismicPlotting not found. [Question]

### ISSUE THREAD

**Issue by Lanzafame** [SeismicJulia/Seismic.jl#1]
Firstly, awesome project! I have been working on a wireline project (currently on the backburner due to other commitments) in Julia and it is great to see others starting to use it for geo-related problems. 

Looking through the tests `reading_rsf_files` uses a package name `SeismicPlotting`. It doesn't seem to exist. I noticed that you use `pycall` to make use of `PyPlot` in the plotting module. Do you plan to replace this with a Julia package in the future?

Cheers for the awesome package. Geophysics was my favourite subject before I moved into IT, so I am a bit rusty but I hope to contribute what I can.

**Comment by aaronstanton** [comment]
Thanks for adding our module! We found that a Julia package can't contain more than one module, so we now use "lazy loading" of the plotting functions. This means that if a user has loaded PyPlot then our plotting functions will load, otherwise they won't. This is convenient for batch processing where we don't need plotting and want to quickly run a code. To use the function SeisPlot you need to do:

using PyPlot,Seismic

I will update the examples accordingly.
